In [4]:
import numpy as np

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(5,2.4)

array([2.4, 2.4, 2.4, 2.4, 2.4])

In [8]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [10]:
x = [2,4,5,6,7,8,9]
x

[2, 4, 5, 6, 7, 8, 9]

In [11]:
a = np.array(x)
a

array([2, 4, 5, 6, 7, 8, 9])

In [12]:
a[0]

np.int64(2)

In [13]:
a[0] = 100
a

array([100,   4,   5,   6,   7,   8,   9])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [25]:
# MULTIDIM ARRAY

In [27]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
n[0,1]

np.int64(2)

In [31]:
n[1]

array([4, 5, 6])

In [32]:
n[:,1]

array([2, 5, 8])

In [36]:
np.random.rand(5,2)

array([[0.54254437, 0.14217005],
       [0.37334076, 0.67413362],
       [0.44183317, 0.43401399],
       [0.61776698, 0.51313824],
       [0.65039718, 0.60103895]])

In [38]:
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [40]:
np.random.randn(5,2)

array([[ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021],
       [ 0.43302619,  1.20303737],
       [-0.96506567,  1.02827408],
       [ 0.22863013,  0.44513761]])

In [41]:
np.random.randint(low=10, high=100, size=(5,2))

array([[23, 35],
       [23, 96],
       [40, 40],
       [99, 22],
       [75, 41]])

In [42]:
##ELEMENTWISEOPERATIONS

In [47]:
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [45]:
b = np.arange(4,9)
b

array([4, 5, 6, 7, 8])

In [48]:
a +1

array([1, 2, 3, 4, 5])

In [49]:
a**2

array([ 0,  1,  4,  9, 16])

In [50]:
a+b

array([ 4,  6,  8, 10, 12])

In [52]:
a.min()

np.int64(0)

In [53]:
a.max()

np.int64(4)

In [54]:
a.std()

np.float64(1.4142135623730951)

In [55]:
a.mean()

np.float64(2.0)

In [56]:
a.sum()

np.int64(10)

In [57]:
n.sum()

np.int64(45)

In [58]:
a >=2

array([False, False,  True,  True,  True])

In [59]:
a < b

array([ True,  True,  True,  True,  True])

In [60]:
a[a>2]

array([3, 4])

In [61]:
a + b

array([ 4,  6,  8, 10, 12])

In [6]:
##PANDAS
import pandas as pd

In [34]:
data = [['Nissan', 'Stanza', 1991],['Hyundai', 'Sonata', 2017],['Lotus', 'Elise', 2010]]

In [35]:
headers = ['Make', 'Model', 'Year']

In [36]:
df = pd.DataFrame(data, columns=headers)

In [37]:
df

      Make   Model  Year
0   Nissan  Stanza  1991
1  Hyundai  Sonata  2017
2    Lotus   Elise  2010

In [38]:
## da dizionario: df = pd.DataFrame(dicts)

In [39]:
df.head(1)

     Make   Model  Year
0  Nissan  Stanza  1991

In [40]:
df.head()

      Make   Model  Year
0   Nissan  Stanza  1991
1  Hyundai  Sonata  2017
2    Lotus   Elise  2010

In [41]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
Name: Make, dtype: str

In [42]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
Name: Make, dtype: str

In [43]:
df[['Make', 'Model']]

      Make   Model
0   Nissan  Stanza
1  Hyundai  Sonata
2    Lotus   Elise

In [44]:
df['id'] = [1,2,3]
df

      Make   Model  Year  id
0   Nissan  Stanza  1991   1
1  Hyundai  Sonata  2017   2
2    Lotus   Elise  2010   3

In [45]:
df['id'] = [10,20,30]
df

      Make   Model  Year  id
0   Nissan  Stanza  1991  10
1  Hyundai  Sonata  2017  20
2    Lotus   Elise  2010  30

In [46]:
del df['id']
df

      Make   Model  Year
0   Nissan  Stanza  1991
1  Hyundai  Sonata  2017
2    Lotus   Elise  2010

In [47]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [48]:
df.loc[1]

Make     Hyundai
Model     Sonata
Year        2017
Name: 1, dtype: object

In [49]:
df.loc[[1,2]]

      Make   Model  Year
1  Hyundai  Sonata  2017
2    Lotus   Elise  2010

In [50]:
df['index']=['a', 'b', 'c']
df

      Make   Model  Year index
0   Nissan  Stanza  1991     a
1  Hyundai  Sonata  2017     b
2    Lotus   Elise  2010     c

In [51]:
df.index=['a', 'b', 'c']
df

      Make   Model  Year index
a   Nissan  Stanza  1991     a
b  Hyundai  Sonata  2017     b
c    Lotus   Elise  2010     c

In [52]:
df.loc[[1,2]]

KeyError: "None of [Index([1, 2], dtype='int64')] are in the [index]"

In [53]:
df.loc[['a','b']]

      Make   Model  Year index
a   Nissan  Stanza  1991     a
b  Hyundai  Sonata  2017     b

In [55]:
df.iloc[[1,2]]

      Make   Model  Year index
b  Hyundai  Sonata  2017     b
c    Lotus   Elise  2010     c

In [57]:
df.reset_index()

  level_0     Make   Model  Year index
0       a   Nissan  Stanza  1991     a
1       b  Hyundai  Sonata  2017     b
2       c    Lotus   Elise  2010     c

In [58]:
df.reset_index(drop=True)

      Make   Model  Year index
0   Nissan  Stanza  1991     a
1  Hyundai  Sonata  2017     b
2    Lotus   Elise  2010     c

In [60]:
df['Year'] /100

a    19.91
b    20.17
c    20.10
Name: Year, dtype: float64

In [61]:
df['Year']>2000

a    False
b     True
c     True
Name: Year, dtype: bool

In [62]:
df[df['Year']>2000]

      Make   Model  Year index
b  Hyundai  Sonata  2017     b
c    Lotus   Elise  2010     c

In [63]:
df[
    (df['Make'] =='Nissan') &
    (df['Year'] <2000)
    ]

     Make   Model  Year index
a  Nissan  Stanza  1991     a

In [67]:
'STr'.lower()

'str'

In [68]:
'sTr'.upper()

'STR'

In [69]:
df['Make'].str.lower()

a     nissan
b    hyundai
c      lotus
Name: Make, dtype: str

In [70]:
'ML zoomcamp'.replace(' ', '_')

'ML_zoomcamp'

In [71]:
df['Make'].str.replace(' ', '_')

a     Nissan
b    Hyundai
c      Lotus
Name: Make, dtype: str

In [73]:
df['Make'].str.replace(' ', '_').str.lower()

a     nissan
b    hyundai
c      lotus
Name: Make, dtype: str

In [75]:
df.Make = df['Make'].str.replace(' ', '_').str.lower()
df

      Make   Model  Year index
a   nissan  Stanza  1991     a
b  hyundai  Sonata  2017     b
c    lotus   Elise  2010     c

In [76]:
df.Year.sum()

np.int64(6018)

In [77]:
df.Year.min()

np.int64(1991)

In [78]:
df.Year.max()

np.int64(2017)

In [80]:
df.Year.mean()

np.float64(2006.0)

In [81]:
df.Year.describe()

count       3.000000
mean     2006.000000
std        13.453624
min      1991.000000
25%      2000.500000
50%      2010.000000
75%      2013.500000
max      2017.000000
Name: Year, dtype: float64

In [82]:
df.describe()

              Year
count     3.000000
mean   2006.000000
std      13.453624
min    1991.000000
25%    2000.500000
50%    2010.000000
75%    2013.500000
max    2017.000000

In [83]:
df.describe().round(2)

          Year
count     3.00
mean   2006.00
std      13.45
min    1991.00
25%    2000.50
50%    2010.00
75%    2013.50
max    2017.00

In [84]:
df.Make.nunique()

3

In [85]:
df.Make.unique()

<StringArray>
['nissan', 'hyundai', 'lotus']
Length: 3, dtype: str

In [86]:
df.isnull()

    Make  Model   Year  index
a  False  False  False  False
b  False  False  False  False
c  False  False  False  False

In [87]:
df.isnull().sum()

Make     0
Model    0
Year     0
index    0
dtype: int64

In [90]:
df.groupby('Make').Model.sum()

Make
hyundai    Sonata
lotus       Elise
nissan     Stanza
Name: Model, dtype: str

In [92]:
df.Make.values

<StringArray>
['nissan', 'hyundai', 'lotus']
Length: 3, dtype: str

In [93]:
df.to_dict(orient='records')

[{'Make': 'nissan', 'Model': 'Stanza', 'Year': 1991, 'index': 'a'},
 {'Make': 'hyundai', 'Model': 'Sonata', 'Year': 2017, 'index': 'b'},
 {'Make': 'lotus', 'Model': 'Elise', 'Year': 2010, 'index': 'c'}]